#Server configuration
server.port=${PORT:8080}
spring.application.name=TelcoNovaP7-Backend

app.jwt.secret=HayQueCambiarEstoPorUnSecretoCombinado-no-olvidar
app.jwt.expiration-ms=1800000

logging.level.org.springframework.security=DEBUG

# Supabase Session Pooler
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# HikariCP para Session Pooler
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.leak-detection-threshold=60000
