CREATE TABLE IF NOT EXISTS usuario (
  id_usuario UUID PRIMARY KEY,
  nombre TEXT NOT NULL,
  numero_iden TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  telefono TEXT NOT NULL,
  rol TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS cliente (
  id_cliente UUID PRIMARY KEY,
  nombre TEXT NOT NULL,
  identificacion TEXT NOT NULL UNIQUE,
  telefono TEXT NOT NULL,
  email TEXT,
  pais TEXT,
  departamento TEXT,
  ciudad TEXT,
  direccion TEXT NOT NULL,
  creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tipo_servicio(
  id_tipo_servicio SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  sla_horas INT
);

CREATE TABLE IF NOT EXISTS prioridad(
  id_prioridad SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  peso INT NOT NULL
);

CREATE TABLE IF NOT EXISTS estado_orden(
  id_estado SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS orden_trabajo(
  id_orden UUID PRIMARY KEY,
  nro_orden TEXT NOT NULL UNIQUE,
  id_cliente UUID NOT NULL REFERENCES cliente(id_cliente) ON DELETE RESTRICT,
  id_tipo_servicio SMALLINT NOT NULL REFERENCES tipo_servicio(id_tipo_servicio) ON DELETE RESTRICT,
  id_prioridad SMALLINT NOT NULL REFERENCES prioridad(id_prioridad) ON DELETE RESTRICT,
  id_estado_actual SMALLINT NOT NULL REFERENCES estado_orden(id_estado) ON DELETE RESTRICT,
  descripcion TEXT,
  creada_por UUID NOT NULL REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
  creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizada_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  programada_en TIMESTAMP WITH TIME ZONE,
  cerrada_en TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS historial_estado(
  id_hist UUID PRIMARY KEY,
  id_orden UUID NOT NULL REFERENCES orden_trabajo(id_orden) ON DELETE CASCADE,
  id_estado SMALLINT NOT NULL REFERENCES estado_orden(id_estado) ON DELETE RESTRICT,
  cambiado_por UUID NOT NULL REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
  cambiado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nota TEXT
);

CREATE TABLE IF NOT EXISTS notificacion(
  id_notif UUID PRIMARY KEY,
  id_orden UUID NOT NULL REFERENCES orden_trabajo(id_orden) ON DELETE CASCADE,
  destinatario_tipo TEXT NOT NULL,
  destinatario_id UUID,
  canal TEXT NOT NULL,
  plantilla TEXT,
  enviado_en TIMESTAMP WITH TIME ZONE,
  estado_envio TEXT NOT NULL DEFAULT 'PENDIENTE',
  detalle TEXT
);
